'use client'
import { QueryClientProvider, Hydrate } from '@tanstack/react-query';
import queryClientInstance from '@/lib/queryCLient';
import './globals.css'
import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import { cache } from "@emotion/css"
import { CacheProvider } from "@emotion/react"
import Head from 'next/head'
import { useState } from 'react';


// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [queryClient] = useState(queryClientInstance);
  return (
    //   {children}
    <html lang="en">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Pokedev</title>
      </Head>
      <body className='font-mont bg-light w-full min-h-screen'>
        <QueryClientProvider client={queryClient}>
          <CacheProvider value={cache}>
            {children}
          </CacheProvider>
        </QueryClientProvider>
      </body>
    </html>
  )
}
